version: "3"

services:
    app-node-api:
        build: .
        command: npm run dev
        ports: 
            - 3333:3333
        volumes: 
            - .:/usr/src/app
        depends_on:
            - db
        
    db:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: senha
        ports: 
            - 5432:5432